[package]
name = "rust_accumulator"
version = "0.1.0"
edition = "2018"

[lib]
name = "rust_accumulator"
crate-type = ["cdylib", "rlib"]

[dependencies]
blstrs = "0.7.1" 
ff = "0.13"
group = "0.13"
rand = "0.8"
rayon = "1.10.0"
halo2_proofs = "0.3.0"
# flint-sys = "0.7.3"
libc = "0.2.154"